server.port=8017
management.server.port=8017

#######################################
#	Database
#######################################
spring.data.mongodb.uri=mongodb://mongo:27017
spring.data.mongodb.database=FSE_GTW

########OPENTELEMETRY################################
otel.traces.exporter=none
otel.logs.exporter=none
otel.metrics.exporter=none
 
otel.propagators=tracecontext,baggage

####### LOGGING OUTPUT FORMAT ############
# Must be one of console, json
#######################################
log.output.format=console